In [2]:
import numpy as np
a = np.arange(6).reshape(2,3) + 10
a

array([[10, 11, 12],
       [13, 14, 15]])

In [3]:
np.argmax(a)

5

In [4]:
np.argmax(a,axis=0)

array([1, 1, 1])

In [5]:
np.argmax(a,axis=1)

array([2, 2])

In [6]:
ind = np.unravel_index(np.argmax(a, axis=None), a.shape)
ind

(1, 2)

In [7]:
a[ind]

15

In [17]:
np.unravel_index(np.argmax(a, axis=0), a.shape[0])

(array([1, 1, 1]),)

In [16]:
np.unravel_index(np.argmax(a, axis=1), a.shape[1])

(array([2, 2]),)

In [1]:
import pandas as pd

In [2]:
pd.DataFrame?